version: "3.9"
services:
  web:
    build: .
    container_name: recipe_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SECRET_KEY=dev-key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
